In [13]:
# Logistic Regression으로 GATE 연산을 학습할 수 있는지 확인!

import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report

# Training Data Set
x_data = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]], dtype=np.float64)

# AND GATE 연산에 대한 t_data
# t_data = np.array([0, 0, 0, 1], dtype=np.float64)

# OR GATE 연산에 대한 t_data
# t_data = np.array([0, 1, 1, 1], dtype=np.float64)

# XOR GATE 연산에 대한 t_data
t_data = np.array([0, 1, 1, 0], dtype=np.float64)


# placeholder
X = tf.placeholder(shape=[None,2], dtype=tf.float32)
T = tf.placeholder(shape=[None,1], dtype=tf.float32)

# Weight & bias
W = tf.Variable(tf.random.normal([2,1]))
b = tf.Variable(tf.random.normal([1]))

# Hypothesis, model
logit = tf.matmul(X,W) + b
H = tf.sigmoid(logit)

# loss function
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,
                                                              labels=T))

# train
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# Session, 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 반복학습
for step in range(30000):
    _, loss_val = sess.run([train, loss],
                           feed_dict={X:x_data,
                                      T:t_data.reshape(-1,1)})
    if step % 3000 == 0:
        print('loss value : {}'.format(loss_val))

loss value : 0.7730317711830139
loss value : 0.6941244602203369
loss value : 0.6931817531585693
loss value : 0.6931490898132324
loss value : 0.6931473016738892
loss value : 0.6931471824645996
loss value : 0.6931471824645996
loss value : 0.6931471824645996
loss value : 0.6931471824645996
loss value : 0.6931471824645996


In [14]:
# evaluation(모델평가)
predict = tf.cast(H >= 0.5, dtype=tf.float32)
predict_val = sess.run(predict, feed_dict={X:x_data})
print(predict_val)

# print(classification_report(정답데이터(1차원), 예측데이터(1차원)))
print(classification_report(t_data, predict_val.ravel()))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지를 확인!

[[0.]
 [0.]
 [0.]
 [1.]]
              precision    recall  f1-score   support

         0.0       0.33      0.50      0.40         2
         1.0       0.00      0.00      0.00         2

    accuracy                           0.25         4
   macro avg       0.17      0.25      0.20         4
weighted avg       0.17      0.25      0.20         4



In [16]:
# DNN으로 XOR GATE 연산을 학습할 수 있는지 확인!

import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report

# Training Data Set
x_data = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]], dtype=np.float64)

# XOR GATE 연산에 대한 t_data
t_data = np.array([0, 1, 1, 0], dtype=np.float64)


# placeholder
X = tf.placeholder(shape=[None,2], dtype=tf.float32)
T = tf.placeholder(shape=[None,1], dtype=tf.float32)

# Weight & bias
W2 = tf.Variable(tf.random.normal([2,10]))
b2 = tf.Variable(tf.random.normal([10]))
layer2 = tf.sigmoid(tf.matmul(X,W2) + b2)

W3 = tf.Variable(tf.random.normal([10,6]))
b3 = tf.Variable(tf.random.normal([6]))
layer3 = tf.sigmoid(tf.matmul(layer2,W3) + b3)

W4 = tf.Variable(tf.random.normal([6,1]))
b4 = tf.Variable(tf.random.normal([1]))


# Hypothesis, model
logit = tf.matmul(layer3,W4) + b4
H = tf.sigmoid(logit)

# loss function
loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=logit,
                                                              labels=T))

# train
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(loss)

# Session, 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 반복학습
for step in range(30000):
    _, loss_val = sess.run([train, loss],
                           feed_dict={X:x_data,
                                      T:t_data.reshape(-1,1)})
    if step % 3000 == 0:
        print('loss value : {}'.format(loss_val))

loss value : 0.6976959705352783
loss value : 0.6453315615653992
loss value : 0.5665238499641418
loss value : 0.4159531593322754
loss value : 0.22907119989395142
loss value : 0.11419809609651566
loss value : 0.06408658623695374
loss value : 0.0411316379904747
loss value : 0.029109908267855644
loss value : 0.02204354852437973


In [17]:
# evaluation(모델평가)
predict = tf.cast(H >= 0.5, dtype=tf.float32)
predict_val = sess.run(predict, feed_dict={X:x_data})
print(predict_val)

# print(classification_report(정답데이터(1차원), 예측데이터(1차원)))
print(classification_report(t_data, predict_val.ravel()))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지를 확인!

[[0.]
 [1.]
 [1.]
 [0.]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         2
         1.0       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [12]:
# Tensorflow 2.x 버전으로 구현해보자!

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD
from sklearn.metrics import classification_report

# Training Data Set
x_data = np.array([[0, 0],
                   [0, 1],
                   [1, 0],
                   [1, 1]], dtype=np.float64)

# XOR GATE 연산에 대한 t_data
t_data = np.array([0, 1, 1, 0], dtype=np.float64)

# Tensorflow 구현
model = Sequential()

model.add(Flatten(input_shape=(2,)))     # input layer
model.add(Dense(units=128,
                activation='sigmoid'))   # 1번째 hidden layer
model.add(Dense(units=32,
                activation='sigmoid'))   # 2번째 hidden layer
model.add(Dense(units=16,
                activation='sigmoid'))   # 3번째 hidden layer
model.add(Dense(units=1,
                activation='sigmoid'))   # output layer

model.compile(optimizer=SGD(learning_rate=1e-2),
              loss='binary_crossentropy')

model.fit(x_data,
          t_data.reshape(-1,1),
          epochs=30000,
          verbose=0)

In [14]:
# evaluation(모델평가)
predict_val = model.predict(x_data)
print(predict_val)
predict_val = tf.cast(predict_val > 0.5, dtype=tf.float32).numpy().ravel()
print(predict_val)

# print(classification_report(정답데이터(1차원), 예측데이터(1차원)))
print(classification_report(t_data, predict_val))
# 결과를 확인해서 logistic regression이 진리표를 학습할 수 있는지를 확인!

# 파라메타 조절을 더 해야 한다!
# 결과가 정상적으로 나와야 한다!

[[0.49988264]
 [0.5009099 ]
 [0.49909103]
 [0.5001188 ]]
[0. 1. 0. 1.]
              precision    recall  f1-score   support

         0.0       0.50      0.50      0.50         2
         1.0       0.50      0.50      0.50         2

    accuracy                           0.50         4
   macro avg       0.50      0.50      0.50         4
weighted avg       0.50      0.50      0.50         4

